#- import_playbook: harmonicio.yml

- hosts: ben-bastion
  roles:
    - bastion

- hosts: all
  roles:
    - haste-common

- hosts: ben-stream-src
  roles:
    - streaming-src

- name: spark master
  hosts: spark-master
  roles:
    - spark
    - spark-master
    - pyspark-notebook-server


- name: spark worker
  hosts: spark-nodes
  roles:
    - spark
    - spark-worker



- hosts: ben-kafka-server
  roles:
    - kafka-server