

- name: Download and Unzip Kafka
  become: true
  unarchive:
    src: http://apache.mirrors.spacedump.net/kafka/2.0.0/kafka_2.11-2.0.0.tgz
    dest: /usr/local/
    # Don't download it again
    creates: /usr/local/kafka_2.11-2.0.0
    remote_src: yes

- name: Symlink to Kafka
  become: true
  file:
    src: /usr/local/kafka_2.11-2.0.0
    dest: /usr/local/kafka
    state: link

# This dir is for the human-readable logs.
# There is a separate 'log' dir for the actual message data, set in server.properties
# (weirdly, lots of these logs seem to be out of data anyway)
- name: Kafka 'logs' dir
  become: true
  file:
    path: /usr/local/kafka/logs
    owner: ubuntu
    state: directory

- name: kafka config
  become: true
  template:
    src: server.properties.j2
    dest: /usr/local/kafka/config/server.properties

# (We control kafka from the benchmarking tool itself.)
#- name: Start kafka
#  become: true
#  shell: /usr/local/kafka/bin/kafka-server-start.sh /usr/local/kafka/config/server.properties

