
- import_tasks: java.yml

# Installs to: /usr/local/spark
- import_tasks: unarchive.yml

#- name: install python3.6
#  become: true
#  package:
#    name: python3.6
#    state: present
#
#- name: uninstall python3.5
#  become: true
#  package:
#    name: python3.5
#    state: absent

# See: https://spark.apache.org/docs/latest/spark-standalone.html#cluster-launch-scripts
# Template: https://github.com/apache/spark/blob/master/conf/spark-env.sh.template

- name: "Spark-env Config file"
  copy:
    content: |
            SPARK_MASTER_HOST="{{ hostvars[item]['ansible_hostname'] }}"
            HADOOP_CONF_DIR="/usr/local/hadoop/conf"
            PYSPARK_PYTHON=/usr/bin/python3
            PYSPARK_DRIVER_PYTHON=/usr/bin/python3
            SPARK_WORKER_PORT=9997
    dest: /usr/local/spark/conf/spark-env.sh
  become: yes
  with_items:
    - "{{ groups['spark-master'] }}"



# Example:
# spark.master                     spark://master:7077
# spark.eventLog.enabled           true
# spark.eventLog.dir               hdfs://namenode:8021/directory
# spark.serializer                 org.apache.spark.serializer.KryoSerializer
# spark.driver.memory              5g
# spark.executor.extraJavaOptions  -XX:+PrintGCDetails -Dkey=value -Dnumbers="one two three"

- name: "Spark-defaults Config file"
  copy:
    content: |
      spark.blockManager.port=9999
      spark.shuffle.service.enabled=True
    dest: /usr/local/spark/conf/spark-defaults.conf
  become: yes
#  with_items:
#    - "{{ groups['spark-master'] }}"
# .... this is a bit of a gotcha... this task gets skipped if there are no hosts in the 'spark-master' group!

# complaints about a missing package here -- run
# sudo sed -ie 's/nova.clouds.archive.ubuntu.com/se.archive.ubuntu.com/' /etc/apt/sources.list
# sudo apt update
- name: install python3-pip
  become: true
  package:
    name: python3-pip
    state: present


- name: install netstat
  become: true
  package:
    name: net-tools
    state: present


# for the million songs
- name: "install h5py"
  become: true
  pip:
    executable: pip3
    name: h5py


# student requested packages
- name: "install tables"
  become: true
  pip:
    executable: pip3
    name: tables


#- name: "install pysam"
#  become: true
#  pip:
#    executable: pip3
#    name: pysam




# TODO: add regex to match any old line
# REQUIRES REBOOT! set it on the driver...
- name: "PYSPARK_PYTHON env variable"
  become: yes
  lineinfile: dest=/etc/environment line="PYSPARK_PYTHON=/usr/bin/python3" state=present

