
- import_tasks: java.yml

# Installs to: /usr/local/spark
- import_tasks: unarchive.yml

# See: https://spark.apache.org/docs/latest/spark-standalone.html#cluster-launch-scripts
# Template: https://github.com/apache/spark/blob/master/conf/spark-env.sh.template

- name: Config file
  copy:
    content: |
            SPARK_MASTER_HOST="{{ hostvars[item]['ansible_hostname'] }}"
            HADOOP_CONF_DIR="/usr/local/hadoop/conf"
    dest: /usr/local/spark/conf/spark-env.sh
  become: yes
  with_items:
    - "{{ groups['spark-master'] }}"

