# TODO: extract variable for Spark file name.

- name: Download and Unzip Apache Spark
  become: true
  unarchive:
    src: https://archive.apache.org/dist/spark/spark-3.0.1/spark-3.0.1-bin-hadoop3.2.tgz
    dest: /usr/local/
    # Don't download it again
    creates: /usr/local/spark-3.0.1-bin-hadoop3.2
    remote_src: yes

- name: Symlink to Spark
  become: true
  file:
    src: /usr/local/spark-3.0.1-bin-hadoop3.2
    dest: /usr/local/spark
    force: true
    state: link


#TODO: not sure these should include 'export'

- name: set SPARK_HOME
  lineinfile:
    path: ~/.profile
    line: "export SPARK_HOME=\"/usr/local/spark\""

- name: add Spark to $PATH
  lineinfile:
    path: ~/.profile
    line: "export PATH=\"$PATH:$SPARK_HOME\""
